# -*- coding: utf-8 -*-
"""
Tafsir fidelity upgrade (v2).

Replaces the tafsirs generated in the previous pass with a more faithful,
mystically-accurate structure:

    {poet} می‌فرماید: «{actual verse}»؛ یعنی {beit meaning}. {fortune}

i.e. the poet's REAL verse is quoted (not a paraphrase), then its meaning is
introduced with «یعنی», then the fortune applies it to the user.

Only tafsirs that were generated by the v1 script are touched (identified by
their exact opening pattern). Hand-written tafsirs are never touched.
"""
import gzip, json, re, collections, sys

BASE = "app/src/main/assets/corpus"
FILES = ["hafez", "khayyam", "saadi", "rumi", "stories"]

POET_FA = {"hafez": "حافظ", "saadi": "سعدی", "rumi": "مولانا", "khayyam": "خیام"}

OPENINGS = {
    "hafez": [
        "حافظ در این غزل می‌فرماید:",
        "این شعرِ حافظ چنین می‌سراید:",
        "حافظ در این بیت‌ها چنین گفته است:",
    ],
    "saadi": [
        "سعدی در این شعر می‌فرماید:",
        "این کلامِ سعدی چنین می‌سراید:",
        "سعدی در این ابیات چنین گفته است:",
    ],
    "rumi": [
        "مولانا در این شعر می‌فرماید:",
        "این کلامِ مولانا چنین می‌سراید:",
        "مولانا در این ابیات چنین گفته است:",
    ],
    "khayyam": [
        "خیام در این رباعی می‌فرماید:",
        "این رباعیِ خیام چنین می‌سراید:",
        "خیام در این ابیات چنین گفته است:",
    ],
}

FORTUNES = {
    "love": [
        "این فال از دلِ عاشقانه‌ات خبر می‌دهد: دلت را پنهان مکن؛ آنچه با خلوص پیشکش کنی، دیر یا زود به تو بازمی‌گردد.",
        "پیامِ این فال برای تو روشن است: عشق، راهِ دل است؛ به آن وفادار بمان و از دشواریِ راه نهراس.",
        "فالِ تو می‌گوید: محبتت دیده می‌شود؛ صبور باش، که وصال، پاداشِ دل‌هایی است که از نیمه‌راه برنگردند.",
    ],
    "wisdom": [
        "فالِ تو دعوتی است به دانایی: پیش از هر گام، اندیشه کن؛ که تدبیر، چراغِ راهِ بی‌برگشت است.",
        "پیامِ این فال: خِرد را با دل همراه کن؛ آنچه امروز درست می‌نماید، فردا نیز روشن خواهد بود.",
        "فالِ تو می‌گوید: حکمت را در سکوت و تأمل بجوی؛ پاسخِ پرسش‌هایت در آرامشِ درونت است.",
    ],
    "decision": [
        "این فال برای تصمیمِ تو آمده است: دودل مباش؛ آنچه دل و عقل با هم تأیید کنند، همان راهِ درست است.",
        "فالِ تو می‌گوید: هنگامِ انتخاب فرا رسیده؛ به نشانه‌های درونت اعتماد کن و گامِ نخست را بردار.",
        "پیامِ این فال: در دوراهی که ایستاده‌ای، سکوت کن و گوش بسپار؛ پاسخ از درونِ خودت بلند می‌شود.",
    ],
    "hope": [
        "این فال بشارت می‌دهد: شبِ نگرانی‌ات به سحر می‌رسد؛ ناامید مباش، که روشنی در راه است.",
        "فالِ تو می‌گوید: امیدت را از دست مده؛ آنچه منتظرش هستی، از راهی می‌رسد که گمانش را نمی‌بری.",
        "پیامِ این فال: دل را به فردا گرم کن؛ که هر سحری، دری تازه به روی امید می‌گشاید.",
    ],
    "new-beginnings": [
        "این فال از آغازی تازه خبر می‌دهد: فصلِ نو در راه است؛ آماده باش و از گذشته سبک‌بار شو.",
        "فالِ تو می‌گوید: فرصتی نو پیش روی توست؛ آن را با دلِ باز بپذیر و از نو آغاز کن.",
        "پیامِ این فال: همچون بهار، زندگی‌ات رنگی تازه می‌گیرد؛ درهای بسته، یکی‌یکی باز می‌شوند.",
    ],
    "joy": [
        "این فال دعوتی است به شادی: غم را زمین بگذار؛ زندگی برای لذت‌های کوچکِ امروز است.",
        "فالِ تو می‌گوید: لبخند را فراموش مکن؛ شادی‌ات را با دیگران قسمت کن تا دوچندان شود.",
        "پیامِ این فال: دلِ شاد، گنجِ بی‌پایان است؛ آن را از هیاهوی روزگار پس بگیر.",
    ],
    "patience": [
        "این فال از صبوری سخن می‌گوید: درختِ صبور میوه می‌دهد؛ سختی‌هایت موقت‌اند و می‌گذرند.",
        "فالِ تو می‌گوید: شتاب مکن؛ آنچه می‌خواهی با عجله به دست نمی‌آید، اما با شکیبایی می‌رسد.",
        "پیامِ این فال: صبر کن و دلت را آرام نگه‌دار؛ که هر انتظاری، سرانجامی نیکو دارد.",
    ],
    "travel": [
        "این فال از سفر می‌گوید: راهی پیش روی توست؛ توشه بردار و با توکل گام بردار.",
        "فالِ تو می‌گوید: مسیرت دراز اما روشن است؛ هر منزل، درسی برای منزلِ بعد دارد.",
        "پیامِ این فال: سفرِ تو آغاز شده؛ از مقصد نترس، که همراهِ تو از تو به تو نزدیک‌تر است.",
    ],
    "effort": [
        "این فال از کوشش می‌گوید: هیچ گنجی بی‌هنر به دست نمی‌آید؛ کارِ امروز، فردای تو را می‌سازد.",
        "فالِ تو می‌گوید: دست از تلاش برندار؛ آنچه می‌کاری، همان را درو خواهی کرد.",
        "پیامِ این فال: کوششت دیده می‌شود؛ پاداش، سهمِ کسی است که از نیمه‌راه برنگردد.",
    ],
    "faith": [
        "این فال از ایمان و توکل می‌گوید: کار را به خدا بسپار، اما پارو زدن را رها مکن.",
        "فالِ تو می‌گوید: دل را با یادِ او آرام کن؛ هر کاری که با نیتِ پاک آغاز شود، فرجامش روشن است.",
        "پیامِ این فال: به وعده‌های راستین امیدوار باش؛ که روزی، از جایی می‌رسد که گمانش را نمی‌بری.",
    ],
    "compassion": [
        "این فال از مهر می‌گوید: با دیگران مهربان باش؛ که نیکی، گم نمی‌شود و به تو بازمی‌گردد.",
        "فالِ تو می‌گوید: دلِ بزرگ، خانهٔ آرامش است؛ ببخش تا سبک شوی.",
        "پیامِ این فال: مهرِ تو دیده می‌شود؛ دستِ بخشنده‌ات، هرگز خالی نمی‌ماند.",
    ],
    "general": [
        "این فال برای تو آمده است: با آرامش قدم بردار و به نشانه‌های راه اعتماد کن.",
        "فالِ تو می‌گوید: نیتت را پاک نگه‌دار؛ که فرجامِ کارِ پاک، نیکوست.",
        "پیامِ این فال: دل را روشن نگه‌دار؛ که هرچه پیش آید، به حکمت است.",
    ],
}

# marks a tafsir produced by the v1 generator (hand-written ones never match)
GENERATED_RE = re.compile(r"(می‌فرماید: «|چنین می‌سراید: «|چنین گفته است: «)")

def trim_sentence(s, limit=150):
    s = s.strip()
    if len(s) <= limit:
        return s
    cut = s[:limit]
    for sep in ("؛ ", ". ", "، ", "؛", "،"):
        idx = cut.rfind(sep)
        if idx > limit * 0.5:
            return cut[: idx + len(sep.strip())].strip()
    return cut.rstrip("، ؛") + "…"

def clean_meaning(m):
    if not m:
        return None
    s = m.strip()
    s = re.split(r"\((?:نکته|منبع|تصحیح|معنی|توجه)\s*[:：]", s)[0]
    s = re.sub(r"^نکته\s*[:：]?\s*", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    s = trim_sentence(s)
    if not s:
        return None
    # lower-case the first letter? keep as-is; meaning is a full sentence already.
    if s[-1] in ".؛!؟":
        s = s[:-1]
    return s or None

def first_couplet(p):
    verses = p.get("verses") or []
    for v in verses:
        if v.get("second"):
            return v
    return verses[0] if verses else None

def generate(p):
    poet = p["poet"]
    pid = p["id"]
    opening = OPENINGS.get(poet, OPENINGS["hafez"])[pid % 3]
    fortune = FORTUNES.get(p.get("themeTag") or "general", FORTUNES["general"])[(pid // 7) % 3]

    # story: moral couplet + fortune (no بیت-معنی)
    if p.get("collection") == "stories":
        cp = first_couplet(p)
        couplet = f"{cp['first'].strip()}؛ {cp['second'].strip()}"
        return f"سعدی در این حکایت می‌فرماید: «{couplet}» {fortune}"

    cp = first_couplet(p)
    if cp is None:
        return f"{opening} {fortune}"
    verse = cp["first"].strip() + (f"؛ {cp['second'].strip()}" if cp.get("second") else "")
    meaning = clean_meaning(cp.get("meaning"))

    if meaning:
        return f"{opening} «{verse}»؛ یعنی {meaning}. {fortune}"
    return f"{opening} «{verse}». {fortune}"

def main():
    regenerated = 0
    for f in FILES:
        path = f"{BASE}/{f}.dat"
        data = json.loads(gzip.open(path, "rt", encoding="utf-8").read())
        for p in data:
            t = p["tafsir"]
            if GENERATED_RE.search(t):
                p["tafsir"] = generate(p)
                regenerated += 1
        gzip.open(path, "wt", encoding="utf-8").write(
            json.dumps(data, ensure_ascii=False, separators=(",", ":"))
        )
    print(f"regenerated (v2, fidelity): {regenerated}")

    # verify: unique, no latin, no newline, no dup
    latin = re.compile(r"[A-Za-zÀ-ÿ]{2,}")
    owners = collections.defaultdict(list)
    bad = []
    for f in FILES:
        data = json.loads(gzip.open(f"{BASE}/{f}.dat", "rt", encoding="utf-8").read())
        for p in data:
            t = p["tafsir"].strip()
            owners[t].append((f, p["id"]))
            if latin.search(t) or "\n" in t or len(t) < 20:
                bad.append((f, p["id"], t[:60]))
    dups = {t: l for t, l in owners.items() if len(l) > 1}
    print(f"duplicated tafsirs: {len(dups)}")
    print(f"latin/newline/short: {len(bad)}")
    for b in bad[:10]:
        print("  BAD:", b)
    if dups or bad:
        sys.exit(1)

if __name__ == "__main__":
    main()
